[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = stm32cube
upload_protocol = stlink
# Ultra-stable settings for custom boards with connection issues
# Configuration ultra-lente pour forcer la connexion
upload_speed = 480
upload_flags = 
    -c reset_config srst_only srst_nogate connect_assert_srst

monitor_speed = 115200

# FreeRTOS include paths
build_flags = 
    -I tunav/Middlewares/Third_Party/FreeRTOS/Source/include
    -I tunav/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    -I tunav/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F

extra_scripts = pre:extra_script.py

[platformio]
include_dir = tunav/Inc
src_dir = tunav/Src
